"""Cache/source-of-truth helper pack."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Iterable

from ..checks import cache_matches_source
from ..scenario_matrix import ScenarioMatrixBuilder


Selector = Callable[[Any], Iterable[Any]]
KeySelector = Callable[[Any], Any]
ValueSelector = Callable[[Any], Any]


@dataclass(frozen=True)
class CachePack:
    """Optional recipe for cache/source consistency checks."""

    cache_selector: Selector
    source_selector: Selector
    key: KeySelector
    value: ValueSelector
    cache_name: str = "cache"
    source_name: str = "source"
    name_prefix: str = "cache"

    def invariants(self) -> tuple[Any, ...]:
        return (
            cache_matches_source(
                name=f"{self.cache_name}_matches_{self.source_name}",
                description=f"{self.cache_name} agrees with {self.source_name} by key",
                cache_selector=self.cache_selector,
                source_selector=self.source_selector,
                key=self.key,
                value=self.value,
                cache_name=self.cache_name,
                source_name=self.source_name,
            ),
        )

    def scenarios(
        self,
        *,
        initial_states: Iterable[Any],
        inputs: tuple[Any, ...],
        workflow: Any = None,
        invariants: tuple[Any, ...] = (),
        max_scenarios: int = 8,
    ) -> tuple[Any, ...]:
        return (
            ScenarioMatrixBuilder(
                name_prefix=self.name_prefix,
                initial_states=initial_states,
                inputs=inputs,
                workflow=workflow,
                invariants=invariants,
                max_scenarios=max_scenarios,
                tags=("cache",),
                notes="generated by CachePack",
            )
            .single_inputs()
            .repeat_same(max_repeats=2)
            .pairwise_orders()
            .build()
        )


__all__ = ["CachePack"]
