"""Deduplication helper pack."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Iterable

from ..checks import at_most_once_by, no_duplicate_by
from ..scenario_matrix import ScenarioMatrixBuilder


Selector = Callable[[Any], Iterable[Any]]
KeySelector = Callable[[Any], Any]


@dataclass(frozen=True)
class DeduplicationPack:
    """Optional recipe for key-based duplicate record checks."""

    record_selector: Selector
    key: KeySelector
    value_name: str = "record"
    name_prefix: str = "deduplication"

    def invariants(self) -> tuple[Any, ...]:
        return (
            no_duplicate_by(
                name=f"no_duplicate_{self.value_name}s",
                description=f"{self.value_name}s are unique by key",
                selector=self.record_selector,
                key=self.key,
                value_name=self.value_name,
            ),
            at_most_once_by(
                name=f"{self.value_name}_at_most_once",
                description=f"each {self.value_name} key appears at most once",
                selector=self.record_selector,
                key=self.key,
                value_name=self.value_name,
            ),
        )

    def scenarios(
        self,
        *,
        initial_states: Iterable[Any],
        inputs: tuple[Any, ...],
        workflow: Any = None,
        invariants: tuple[Any, ...] = (),
        max_scenarios: int = 12,
    ) -> tuple[Any, ...]:
        return (
            ScenarioMatrixBuilder(
                name_prefix=self.name_prefix,
                initial_states=initial_states,
                inputs=inputs,
                workflow=workflow,
                invariants=invariants,
                max_scenarios=max_scenarios,
                tags=("deduplication",),
                notes="generated by DeduplicationPack",
            )
            .single_inputs()
            .repeat_same(max_repeats=2)
            .pairwise_orders()
            .aba()
            .build()
        )


__all__ = ["DeduplicationPack"]
