"""Retry helper pack."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Iterable

from ..checks import at_most_once_by
from ..scenario_matrix import ScenarioMatrixBuilder


Selector = Callable[[Any], Iterable[Any]]
KeySelector = Callable[[Any], Any]


@dataclass(frozen=True)
class RetryPack:
    """Optional recipe for retry and repeated-input checks."""

    attempt_selector: Selector | None = None
    key: KeySelector | None = None
    value_name: str = "attempt"
    name_prefix: str = "retry"
    suggested_max_sequence_length: int = 2

    def invariants(self) -> tuple[Any, ...]:
        if self.attempt_selector is None or self.key is None:
            return ()
        return (
            at_most_once_by(
                name=f"{self.value_name}_at_most_once",
                description=f"retry should not create repeated {self.value_name}s for one key",
                selector=self.attempt_selector,
                key=self.key,
                value_name=self.value_name,
            ),
        )

    def scenarios(
        self,
        *,
        initial_states: Iterable[Any],
        inputs: tuple[Any, ...],
        workflow: Any = None,
        invariants: tuple[Any, ...] = (),
        max_scenarios: int = 12,
    ) -> tuple[Any, ...]:
        return (
            ScenarioMatrixBuilder(
                name_prefix=self.name_prefix,
                initial_states=initial_states,
                inputs=inputs,
                workflow=workflow,
                invariants=invariants,
                max_scenarios=max_scenarios,
                tags=("retry", "repeated_input"),
                notes="generated by RetryPack",
            )
            .single_inputs()
            .repeat_same(max_repeats=2)
            .pairwise_orders()
            .aba()
            .build()
        )


__all__ = ["RetryPack"]
