"""Side-effect helper pack."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Iterable

from ..checks import at_most_once_by
from ..scenario_matrix import ScenarioMatrixBuilder


Selector = Callable[[Any], Iterable[Any]]
KeySelector = Callable[[Any], Any]


@dataclass(frozen=True)
class SideEffectPack:
    """Optional recipe for at-most-once side-effect checks."""

    side_effect_selector: Selector
    key: KeySelector
    value_name: str = "side_effect"
    name_prefix: str = "side_effect"

    def invariants(self) -> tuple[Any, ...]:
        return (
            at_most_once_by(
                name=f"{self.value_name}_at_most_once",
                description=f"each {self.value_name} key is emitted at most once",
                selector=self.side_effect_selector,
                key=self.key,
                value_name=self.value_name,
            ),
        )

    def scenarios(
        self,
        *,
        initial_states: Iterable[Any],
        inputs: tuple[Any, ...],
        workflow: Any = None,
        invariants: tuple[Any, ...] = (),
        max_scenarios: int = 12,
    ) -> tuple[Any, ...]:
        return (
            ScenarioMatrixBuilder(
                name_prefix=self.name_prefix,
                initial_states=initial_states,
                inputs=inputs,
                workflow=workflow,
                invariants=invariants,
                max_scenarios=max_scenarios,
                tags=("side_effect", "repeated_input"),
                notes="generated by SideEffectPack",
            )
            .single_inputs()
            .repeat_same(max_repeats=2)
            .pairwise_orders()
            .aba()
            .build()
        )


__all__ = ["SideEffectPack"]
