"""flowguard: executable function-flow models for model-first engineering."""

from .adoption import (
    ADOPTION_STATUSES,
    AdoptionCommandResult,
    AdoptionLogEntry,
    AdoptionTimer,
    append_jsonl,
    append_markdown_log,
    make_adoption_log_entry,
    utc_now_text,
)
from .adoption_audit import AdoptionAuditFinding, AdoptionAuditReport, audit_flowguard_adoption
from .audit import ModelQualityAuditReport, ModelQualityFinding, audit_model
from .checks import (
    all_items_have_source,
    at_most_once_by,
    cache_matches_source,
    forbid_label_after,
    no_contradictory_values,
    no_duplicate_by,
    no_duplicate_values,
    only_named_block_writes,
    require_label,
    require_label_order,
    require_reachable,
    state_invariant,
)
from .baseline import (
    EvidenceBaselineReport,
    EvidenceCaseResult,
    build_evidence_baseline_report,
)
from .benchmark import BenchmarkScorecard, build_benchmark_scorecard
from .corpus import (
    ProblemCase,
    ProblemCorpus,
    ProblemCorpusReport,
    build_problem_corpus_report,
)
from .executable import (
    ExecutableCaseResult,
    ExecutableCorpusReport,
    build_executable_corpus_report,
)
from .conformance import (
    ConformanceReport,
    ConformanceRule,
    ConformanceViolation,
    default_conformance_rules,
    replay_trace,
)
from .contract import (
    ContractCheckReport,
    ContractViolation,
    FunctionContract,
    check_refinement_projection,
    check_trace_contracts,
)
from .coverage import (
    BenchmarkCoverageAudit,
    build_benchmark_coverage_audit,
)
from .core import FunctionBlock, FunctionResult, Invariant, InvariantResult
from .explorer import Explorer, ReachabilityCondition, enumerate_input_sequences
from .export import to_json_text, to_jsonable
from .loop import GraphEdge, LoopCheckConfig, LoopCheckReport, check_loops, tarjan_scc
from .progress import (
    BoundedEventuallyProperty,
    EventuallyProperty,
    ProgressCheckConfig,
    ProgressCheckReport,
    ProgressFinding,
    check_progress,
)
from .minimize import (
    MinimizedCounterexample,
    ReductionStep,
    minimize_failing_sequence,
    minimize_report_counterexample,
)
from .packs import CachePack, DeduplicationPack, RetryPack, SideEffectPack
from .plan import FlowGuardCheckPlan, ScenarioMatrixConfig
from .pytest_adapter import assert_no_executable_corpus_regression, assert_report_ok
from .report import (
    CheckReport,
    DeadBranch,
    ExceptionBranch,
    InvariantViolation,
    ReachabilityFailure,
)
from .replay import ReplayAdapter, ReplayObservation
from .review import (
    OracleReviewResult,
    ScenarioReviewReport,
    review_scenario,
    review_scenarios,
    scenario_status_explanation,
    scenario_status_ok,
)
from .risk import RiskProfile, SkippedCheck
from .runner import run_model_first_checks
from .scenario import (
    OracleCheckResult,
    Scenario,
    ScenarioExpectation,
    ScenarioRun,
    run_exact_sequence,
)
from .scenario_matrix import ScenarioMatrixBuilder
from .schema import ArtifactEnvelope, SCHEMA_VERSION, make_artifact, report_artifact, trace_artifact
from .summary_report import (
    FlowGuardSection,
    FlowGuardSummaryReport,
    build_flowguard_summary_report,
    section_from_audit_report,
    section_from_check_report,
    section_from_ok_report,
    section_from_scenario_report,
)
from .templates import (
    TemplateFile,
    adoption_template_files,
    maintenance_workflow_template_files,
    project_template_files,
    write_template_files,
)
from .trace import Trace, TraceStep
from .workflow import Workflow, WorkflowPath, WorkflowRun

CORE_API = (
    "FunctionBlock",
    "FunctionResult",
    "Invariant",
    "InvariantResult",
    "Workflow",
    "WorkflowPath",
    "WorkflowRun",
    "Explorer",
    "ReachabilityCondition",
    "CheckReport",
    "DeadBranch",
    "ExceptionBranch",
    "InvariantViolation",
    "ReachabilityFailure",
    "Trace",
    "TraceStep",
    "enumerate_input_sequences",
)

MODELING_HELPER_API = (
    "all_items_have_source",
    "at_most_once_by",
    "cache_matches_source",
    "forbid_label_after",
    "no_contradictory_values",
    "no_duplicate_by",
    "no_duplicate_values",
    "only_named_block_writes",
    "require_label",
    "require_label_order",
    "require_reachable",
    "state_invariant",
    "MinimizedCounterexample",
    "ReductionStep",
    "minimize_failing_sequence",
    "minimize_report_counterexample",
    "Scenario",
    "ScenarioExpectation",
    "ScenarioRun",
    "OracleCheckResult",
    "OracleReviewResult",
    "ScenarioReviewReport",
    "review_scenario",
    "review_scenarios",
    "run_exact_sequence",
    "scenario_status_explanation",
    "scenario_status_ok",
    "ScenarioMatrixBuilder",
    "CachePack",
    "DeduplicationPack",
    "RetryPack",
    "SideEffectPack",
    "ConformanceReport",
    "ConformanceRule",
    "ConformanceViolation",
    "default_conformance_rules",
    "replay_trace",
    "ReplayAdapter",
    "ReplayObservation",
    "FunctionContract",
    "ContractCheckReport",
    "ContractViolation",
    "check_refinement_projection",
    "check_trace_contracts",
    "GraphEdge",
    "LoopCheckConfig",
    "LoopCheckReport",
    "check_loops",
    "tarjan_scc",
    "BoundedEventuallyProperty",
    "EventuallyProperty",
    "ProgressCheckConfig",
    "ProgressCheckReport",
    "ProgressFinding",
    "check_progress",
)

REPORTING_HELPER_API = (
    "RiskProfile",
    "SkippedCheck",
    "FlowGuardCheckPlan",
    "ScenarioMatrixConfig",
    "run_model_first_checks",
    "ModelQualityAuditReport",
    "ModelQualityFinding",
    "audit_model",
    "FlowGuardSection",
    "FlowGuardSummaryReport",
    "build_flowguard_summary_report",
    "section_from_audit_report",
    "section_from_check_report",
    "section_from_ok_report",
    "section_from_scenario_report",
    "AdoptionAuditFinding",
    "AdoptionAuditReport",
    "audit_flowguard_adoption",
    "AdoptionCommandResult",
    "AdoptionLogEntry",
    "AdoptionTimer",
    "ADOPTION_STATUSES",
    "append_jsonl",
    "append_markdown_log",
    "make_adoption_log_entry",
    "utc_now_text",
    "ArtifactEnvelope",
    "SCHEMA_VERSION",
    "make_artifact",
    "report_artifact",
    "trace_artifact",
    "to_json_text",
    "to_jsonable",
)

EVIDENCE_API = (
    "EvidenceBaselineReport",
    "EvidenceCaseResult",
    "build_evidence_baseline_report",
    "BenchmarkScorecard",
    "build_benchmark_scorecard",
    "BenchmarkCoverageAudit",
    "build_benchmark_coverage_audit",
    "ProblemCase",
    "ProblemCorpus",
    "ProblemCorpusReport",
    "build_problem_corpus_report",
    "ExecutableCaseResult",
    "ExecutableCorpusReport",
    "build_executable_corpus_report",
    "assert_no_executable_corpus_regression",
    "assert_report_ok",
    "TemplateFile",
    "adoption_template_files",
    "maintenance_workflow_template_files",
    "project_template_files",
    "write_template_files",
)

API_SURFACE = {
    "core": CORE_API,
    "modeling_helpers": MODELING_HELPER_API,
    "reporting_helpers": REPORTING_HELPER_API,
    "evidence": EVIDENCE_API,
}

__all__ = [
    "AdoptionCommandResult",
    "AdoptionAuditFinding",
    "AdoptionAuditReport",
    "AdoptionLogEntry",
    "AdoptionTimer",
    "ADOPTION_STATUSES",
    "CheckReport",
    "CachePack",
    "ConformanceReport",
    "ConformanceRule",
    "ConformanceViolation",
    "ContractCheckReport",
    "ContractViolation",
    "BoundedEventuallyProperty",
    "DeadBranch",
    "EvidenceBaselineReport",
    "EvidenceCaseResult",
    "EventuallyProperty",
    "BenchmarkScorecard",
    "BenchmarkCoverageAudit",
    "ExecutableCaseResult",
    "ExecutableCorpusReport",
    "ExceptionBranch",
    "Explorer",
    "DeduplicationPack",
    "FlowGuardCheckPlan",
    "FunctionBlock",
    "FunctionContract",
    "FunctionResult",
    "GraphEdge",
    "Invariant",
    "InvariantResult",
    "InvariantViolation",
    "LoopCheckConfig",
    "LoopCheckReport",
    "OracleCheckResult",
    "OracleReviewResult",
    "ProblemCase",
    "ProblemCorpus",
    "ProblemCorpusReport",
    "ProgressCheckConfig",
    "ProgressCheckReport",
    "ProgressFinding",
    "ReachabilityCondition",
    "ReachabilityFailure",
    "ReplayAdapter",
    "ReplayObservation",
    "RetryPack",
    "RiskProfile",
    "Scenario",
    "ScenarioExpectation",
    "ScenarioMatrixConfig",
    "ScenarioReviewReport",
    "ScenarioRun",
    "SideEffectPack",
    "SkippedCheck",
    "ArtifactEnvelope",
    "API_SURFACE",
    "CORE_API",
    "EVIDENCE_API",
    "MODELING_HELPER_API",
    "REPORTING_HELPER_API",
    "SCHEMA_VERSION",
    "TemplateFile",
    "Trace",
    "TraceStep",
    "Workflow",
    "WorkflowPath",
    "WorkflowRun",
    "FlowGuardSection",
    "FlowGuardSummaryReport",
    "MinimizedCounterexample",
    "ModelQualityAuditReport",
    "ModelQualityFinding",
    "ReductionStep",
    "ScenarioMatrixBuilder",
    "check_loops",
    "check_progress",
    "check_refinement_projection",
    "check_trace_contracts",
    "assert_no_executable_corpus_regression",
    "assert_report_ok",
    "all_items_have_source",
    "append_jsonl",
    "append_markdown_log",
    "adoption_template_files",
    "maintenance_workflow_template_files",
    "audit_flowguard_adoption",
    "at_most_once_by",
    "build_executable_corpus_report",
    "build_benchmark_scorecard",
    "build_benchmark_coverage_audit",
    "build_evidence_baseline_report",
    "build_flowguard_summary_report",
    "build_problem_corpus_report",
    "audit_model",
    "cache_matches_source",
    "enumerate_input_sequences",
    "default_conformance_rules",
    "forbid_label_after",
    "minimize_failing_sequence",
    "minimize_report_counterexample",
    "no_contradictory_values",
    "no_duplicate_by",
    "no_duplicate_values",
    "only_named_block_writes",
    "require_label",
    "require_label_order",
    "require_reachable",
    "replay_trace",
    "review_scenario",
    "review_scenarios",
    "scenario_status_explanation",
    "scenario_status_ok",
    "run_model_first_checks",
    "run_exact_sequence",
    "make_artifact",
    "make_adoption_log_entry",
    "project_template_files",
    "report_artifact",
    "section_from_audit_report",
    "section_from_check_report",
    "section_from_ok_report",
    "section_from_scenario_report",
    "state_invariant",
    "tarjan_scc",
    "trace_artifact",
    "to_json_text",
    "to_jsonable",
    "utc_now_text",
    "write_template_files",
]
