"""Current owner-receipt authority for the persistent reverse-surface map.

Model revisions intentionally publish evidence only for the affected closure of
that revision.  A persistent reverse-surface map has a different denominator:
it keeps one semantic owner for every currently observed implementation
surface.  This module composes a separate, explicit current authority for
that denominator from the exact current model-regression leaf receipts.  It is
not a reader for an older authority and it never reuses a receipt merely
because its route name matches.
"""

from __future__ import annotations

from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import sys
from typing import Any, Mapping, Sequence

from .evidence_receipts import (
    RECEIPT_STATUS_PASS,
    EvidenceReceipt,
    fingerprint_value,
    load_evidence_receipt,
    receipt_path,
    verify_evidence_receipt,
)
from .model_revision_builder import (
    _VerifiedModelParent,
    _verify_model_parent_receipt,
)
from .model_authority_store import load_current_model_authority_state
from .validation_ownership import (
    OWNER_RECEIPT_KIND,
    OWNER_RECEIPT_SCOPE,
    ValidationOwnerContract,
    build_child_bound_owner_receipt_context,
    build_owner_current,
    find_reusable_owner_receipt,
    save_child_bound_owner_receipt,
)


REVERSE_SURFACE_OWNER_AUTHORITY_SCHEMA = (
    "flowguard.implementation_surface_owner_receipt_authority.v1"
)
REVERSE_SURFACE_OWNER_AUTHORITY_RELATIVE_PATH = (
    ".flowguard/evidence/reverse-surface-owner-authority/current.json"
)
RECEIPT_ROOT_RELATIVE_PATH = ".flowguard/evidence/model-owner-receipts"
DISCOVERY_RELATIVE_PATH = ".flowguard/structure/reverse-surfaces/current-discovery.json"
OWNER_BINDINGS_RELATIVE_PATH = ".flowguard/structure/owner-bindings.json"
MAP_RELATIVE_PATH = ".flowguard/structure/reverse-surfaces/implementation-surface-map.json"


class ReverseSurfaceOwnerAuthorityError(ValueError):
    """Raised when a current reverse owner authority is absent or stale."""


def _canonical_hash(value: Any) -> str:
    return fingerprint_value(value)


def _read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ReverseSurfaceOwnerAuthorityError(
            f"cannot read current reverse owner authority input {path}: {exc}"
        ) from exc


def _write_json(path: Path, value: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )


def _relative_path(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _sha256_path(root: Path, relative_path: str) -> str:
    path = (root / relative_path).resolve()
    if root.resolve() not in path.parents:
        raise ReverseSurfaceOwnerAuthorityError(
            f"current reverse owner authority path escapes project root: {relative_path}"
        )
    if not path.is_file():
        raise ReverseSurfaceOwnerAuthorityError(
            f"current reverse owner authority input is missing: {relative_path}"
        )
    return f"sha256:{hashlib.sha256(path.read_bytes()).hexdigest()}"


def _owner_binding_projection(value: Any, *, parent_key: str = "") -> Any:
    """Project map content without receipt identities generated by this authority.

    The persistent reverse authority must notice semantic/ownership changes,
    but it must not invalidate itself merely because the semantic map records
    the authority's own current receipt IDs.  Those IDs are immutable evidence
    outputs, not semantic inputs.  We therefore retain all map structure and
    non-owner proof references while removing only the self-generated identity
    fields and derived hashes.  The full map remains independently audited;
    this projection is only the owner-receipt contract binding.
    """

    if isinstance(value, Mapping):
        projected: dict[str, Any] = {}
        for raw_key, raw_value in value.items():
            key = str(raw_key)
            if key == "authoring_fingerprint":
                # This is derived from the full map and necessarily changes
                # when the current authority IDs are materialized.
                continue
            if key in {"owner_receipt_id", "owner_receipt_fingerprint"}:
                continue
            if parent_key == "owner_receipt_identities" and key in {
                "receipt_id",
                "receipt_fingerprint",
            }:
                continue
            if key == "join_fingerprint" and parent_key == "current_authority_join":
                # Recomputed from the owner identities, including the IDs
                # intentionally removed from this stable projection.
                continue
            if key in {"receipt_refs", "terminal_receipt_refs"}:
                if isinstance(raw_value, (list, tuple)):
                    projected[key] = sorted(
                        {
                            str(item)
                            for item in raw_value
                            if "validation-owner:" not in str(item)
                        }
                    )
                else:
                    projected[key] = _owner_binding_projection(
                        raw_value, parent_key=key
                    )
                continue
            projected[key] = _owner_binding_projection(raw_value, parent_key=key)
        return projected
    if isinstance(value, list):
        return [
            _owner_binding_projection(item, parent_key=parent_key)
            for item in value
        ]
    if isinstance(value, tuple):
        return [
            _owner_binding_projection(item, parent_key=parent_key)
            for item in value
        ]
    if parent_key == "owner_receipt_identities" and isinstance(value, str):
        # Kept for clarity if a future projection supplies scalar identities;
        # object rows are handled by the key-level filters above.
        return "<CURRENT_OWNER_RECEIPT>"
    return value


def _semantic_map_binding_fingerprint(root: Path) -> str:
    """Return the stable owner-binding identity for the current semantic map."""

    path = (root / MAP_RELATIVE_PATH).resolve()
    if root.resolve() not in path.parents:
        raise ReverseSurfaceOwnerAuthorityError(
            f"current reverse owner authority path escapes project root: {MAP_RELATIVE_PATH}"
        )
    if not path.is_file():
        raise ReverseSurfaceOwnerAuthorityError(
            f"current reverse owner authority input is missing: {MAP_RELATIVE_PATH}"
        )
    payload = _read_json(path)
    if not isinstance(payload, Mapping):
        raise ReverseSurfaceOwnerAuthorityError(
            "current reverse semantic map must be an object"
        )
    return _canonical_hash(_owner_binding_projection(payload))


def _load_owner_bindings(root: Path) -> tuple[dict[str, tuple[str, ...]], str]:
    payload = _read_json(root / OWNER_BINDINGS_RELATIVE_PATH)
    if not isinstance(payload, Mapping):
        raise ReverseSurfaceOwnerAuthorityError("owner-bindings authority must be an object")
    if payload.get("schema") != "flowguard.native_owner_model_bindings.v1":
        raise ReverseSurfaceOwnerAuthorityError("owner-bindings authority schema is not current")
    rows = payload.get("bindings")
    if not isinstance(rows, list) or not rows:
        raise ReverseSurfaceOwnerAuthorityError("owner-bindings authority has no bindings")
    result: dict[str, tuple[str, ...]] = {}
    for index, row in enumerate(rows):
        if not isinstance(row, Mapping):
            raise ReverseSurfaceOwnerAuthorityError(
                f"owner-bindings row {index} is not an object"
            )
        route = str(row.get("owner_route", "")).strip()
        models = tuple(sorted(str(item).strip() for item in row.get("model_ids", ()) if str(item).strip()))
        if not route or not models or route in result or len(models) != len(set(models)):
            raise ReverseSurfaceOwnerAuthorityError(
                f"owner-bindings row {index} is not an exact current binding"
            )
        result[route] = models
    return result, _canonical_hash(payload)


def _load_current_discovery(root: Path) -> tuple[str, int]:
    payload = _read_json(root / DISCOVERY_RELATIVE_PATH)
    if not isinstance(payload, Mapping) or payload.get("status") != "passed":
        raise ReverseSurfaceOwnerAuthorityError(
            "current reverse discovery is not a terminal passed observation"
        )
    fingerprint = str(payload.get("discovery_fingerprint", "")).strip()
    rows = payload.get("surfaces")
    if not fingerprint.startswith("sha256:") or not isinstance(rows, list) or not rows:
        raise ReverseSurfaceOwnerAuthorityError(
            "current reverse discovery identity or denominator is invalid"
        )
    return fingerprint, len(rows)


def _load_persistent_owner_routes(root: Path) -> tuple[str, ...]:
    payload = _read_json(root / MAP_RELATIVE_PATH)
    if not isinstance(payload, Mapping):
        raise ReverseSurfaceOwnerAuthorityError("current reverse map must be an object")
    if payload.get("schema_version") != "flowguard.implementation_surface_map.v1":
        raise ReverseSurfaceOwnerAuthorityError(
            "current reverse map schema is not current"
        )
    rows = payload.get("surfaces")
    groups = payload.get("component_groups")
    if not isinstance(rows, list) or not isinstance(groups, list):
        raise ReverseSurfaceOwnerAuthorityError("current reverse map owner denominator is invalid")
    routes: set[str] = set()
    for row in [*rows, *groups]:
        if not isinstance(row, Mapping):
            raise ReverseSurfaceOwnerAuthorityError("current reverse map owner row is invalid")
        route = str(row.get("owner", "")).strip()
        if not route:
            raise ReverseSurfaceOwnerAuthorityError("current reverse map contains an ownerless row")
        routes.add(route)
    if not routes:
        raise ReverseSurfaceOwnerAuthorityError("current reverse map has no persistent owner routes")
    return tuple(sorted(routes))


def _authority_identity(state: Any) -> dict[str, str]:
    head = getattr(state, "head", None)
    if head is None:
        raise ReverseSurfaceOwnerAuthorityError("current model authority has no head")
    result = {
        "head_fingerprint": str(getattr(head, "fingerprint", "")).strip(),
        "snapshot_fingerprint": str(getattr(head, "snapshot_fingerprint", "")).strip(),
        "revision_set_fingerprint": str(
            getattr(head, "accepted_revision_set_fingerprint", "")
        ).strip(),
        "activation_receipt_fingerprint": str(
            getattr(head, "activation_receipt_fingerprint", "")
        ).strip(),
    }
    if any(not value.startswith("sha256:") for value in result.values()):
        raise ReverseSurfaceOwnerAuthorityError("current model authority identity is invalid")
    return result


def build_reverse_owner_contract(
    *,
    route: str,
    model_ids: Sequence[str],
    authority_identity: Mapping[str, str],
    discovery_fingerprint: str,
    owner_bindings_fingerprint: str,
    route_set_fingerprint: str,
    model_parent_fingerprint: str,
    semantic_map_fingerprint: str,
    child_receipts: Mapping[str, EvidenceReceipt],
) -> ValidationOwnerContract:
    """Derive the one current contract for a persistent reverse owner."""

    route = str(route).strip()
    normalized_models = tuple(sorted(str(item).strip() for item in model_ids if str(item).strip()))
    if (
        not route
        or not normalized_models
        or not str(semantic_map_fingerprint).startswith("sha256:")
    ):
        raise ReverseSurfaceOwnerAuthorityError("reverse owner contract needs route and model ids")
    projected: list[tuple[str, str]] = [
        ("reverse-surface:authority-head", authority_identity["head_fingerprint"]),
        ("reverse-surface:authority-snapshot", authority_identity["snapshot_fingerprint"]),
        ("reverse-surface:authority-revision", authority_identity["revision_set_fingerprint"]),
        ("reverse-surface:authority-activation", authority_identity["activation_receipt_fingerprint"]),
        ("reverse-surface:discovery", discovery_fingerprint),
        ("reverse-surface:owner-bindings", owner_bindings_fingerprint),
        ("reverse-surface:owner-route-set", route_set_fingerprint),
        ("reverse-surface:model-parent", model_parent_fingerprint),
        # The stable semantic/ownership projection is the source of the
        # persistent reverse denominator.  The raw map also records the
        # receipts produced by this authority; binding those generated IDs
        # into every owner contract would make the authority self-invalidating
        # after its own normal publication.
        ("reverse-surface:semantic-map", semantic_map_fingerprint),
    ]
    projected.extend(
        (f"reverse-surface:model-child:{model_id}", child_receipts[model_id].fingerprint)
        for model_id in normalized_models
    )
    return ValidationOwnerContract(
        owner_id=route,
        command=(
            sys.executable,
            "scripts/author_current_reverse_surface_owner_authority.py",
            "--owner-route",
            route,
        ),
        input_patterns=(),
        obligation_ids=(f"reverse-surface-owner:{route}",),
        projected_inputs=tuple(projected),
        dependency_owner_ids=tuple(f"model:{model_id}" for model_id in normalized_models),
        resource_keys=(f"reverse-surface-owner:{route}",),
    )


def _receipt_root_for_parent(root: Path, parent_path: Path) -> Path:
    """Resolve the receipt store that owns one explicit model parent.

    Model-regression parents are content-addressed beneath
    ``<receipt-root>/model-parents``.  Using the historical default store here
    made an otherwise valid parent from an isolated work receipt root appear
    to have missing children (and could surface as an ambiguous/stale retry).
    The parent path is already an explicit authority input, so derive its
    sibling store while retaining the default for legacy direct callers.
    """

    root_path = root.resolve()
    parent_path = parent_path.resolve()
    candidate = parent_path.parent.parent
    if (
        candidate != root_path
        and root_path in candidate.parents
        and parent_path.parent.name == "model-parents"
    ):
        return candidate
    return root_path / RECEIPT_ROOT_RELATIVE_PATH


def _parent_for_current(
    root: Path,
    parent_path: Path,
    *,
    receipt_root: Path | None = None,
) -> _VerifiedModelParent:
    try:
        return _verify_model_parent_receipt(
            root,
            parent_path,
            receipt_root or _receipt_root_for_parent(root, parent_path),
        )
    except Exception as exc:
        raise ReverseSurfaceOwnerAuthorityError(
            f"current reverse owner authority model parent is not exact-current: {exc}"
        ) from exc


def _receipt_path(
    root: Path,
    receipt: EvidenceReceipt,
    *,
    receipt_root: Path | None = None,
) -> str:
    # Owner receipts use the canonical content-addressed filename derived from
    # their immutable receipt id.  Resolving that path directly avoids a full
    # directory glob and JSON parse for every owner whenever the store holds
    # thousands of historical receipts.  Missing files remain a hard failure;
    # there is no route-name or broad-scan fallback.
    path = receipt_path(
        receipt.receipt_id,
        root,
        output_directory=receipt_root or root / RECEIPT_ROOT_RELATIVE_PATH,
    )
    if not path.is_file():
        raise ReverseSurfaceOwnerAuthorityError(
            f"current reverse owner receipt is not addressable in the canonical store: {receipt.receipt_id}"
        )
    return _relative_path(root, path) + "#" + receipt.receipt_id


def build_current_reverse_surface_owner_authority(
    root: str | Path,
    *,
    model_parent_receipt: str | Path,
) -> dict[str, Any]:
    """Compose and publish the complete current persistent reverse owner authority."""

    root_path = Path(root).resolve()
    parent_path = Path(model_parent_receipt).resolve()
    if root_path not in parent_path.parents:
        raise ReverseSurfaceOwnerAuthorityError("model parent receipt must stay inside the project")
    receipt_root = _receipt_root_for_parent(root_path, parent_path)
    state = load_current_model_authority_state(root_path)
    authority_identity = _authority_identity(state)
    discovery_fingerprint, discovered_surface_count = _load_current_discovery(root_path)
    bindings, bindings_fingerprint = _load_owner_bindings(root_path)
    routes = _load_persistent_owner_routes(root_path)
    # Bind receipts to stable semantic/owner content.  The map itself records
    # the current receipt identities, so hashing its raw bytes here would make
    # the authority self-invalidating on every normal publication.
    semantic_map_fingerprint = _semantic_map_binding_fingerprint(root_path)
    unknown_routes = sorted(set(routes) - set(bindings))
    if unknown_routes:
        raise ReverseSurfaceOwnerAuthorityError(
            "reverse map uses owner routes absent from current owner-bindings: "
            + ", ".join(unknown_routes)
        )
    route_rows = [
        {"owner_route": route, "model_ids": list(bindings[route])}
        for route in routes
    ]
    route_set_fingerprint = _canonical_hash(route_rows)
    parent = _parent_for_current(root_path, parent_path, receipt_root=receipt_root)
    parent_fingerprint = parent.fingerprint
    all_model_ids = {
        model_id
        for route in routes
        for model_id in bindings[route]
    }
    missing_models = sorted(all_model_ids - set(parent.contracts_by_model))
    if missing_models:
        raise ReverseSurfaceOwnerAuthorityError(
            "reverse owner route references models absent from the current full parent: "
            + ", ".join(missing_models)
        )
    child_contracts = tuple(
        parent.contracts_by_model[model_id]
        for model_id in sorted(all_model_ids)
    )
    child_receipts = {
        model_id: parent.receipts_by_model[model_id]
        for model_id in sorted(all_model_ids)
    }
    contracts = tuple(
        build_reverse_owner_contract(
            route=route,
            model_ids=bindings[route],
            authority_identity=authority_identity,
            discovery_fingerprint=discovery_fingerprint,
            owner_bindings_fingerprint=bindings_fingerprint,
            route_set_fingerprint=route_set_fingerprint,
            model_parent_fingerprint=parent_fingerprint,
            semantic_map_fingerprint=semantic_map_fingerprint,
            child_receipts=child_receipts,
        )
        for route in routes
    )
    all_contracts = tuple([*child_contracts, *contracts])
    published: list[dict[str, Any]] = []
    # Reuse only exact-current aggregate receipts from the immediately prior
    # authority identity.  The candidate inventory is addressed by the prior
    # immutable IDs when available; no broad historical scan or route-name
    # fallback is permitted.
    prior_receipt_ids: list[str] = []
    prior_authority_path = root_path / REVERSE_SURFACE_OWNER_AUTHORITY_RELATIVE_PATH
    try:
        prior_payload = _read_json(prior_authority_path)
        prior_rows = prior_payload.get("owner_receipt_identities", [])
        if isinstance(prior_rows, list):
            prior_receipt_ids = sorted(
                {
                    str(row.get("receipt_id", "")).strip()
                    for row in prior_rows
                    if isinstance(row, Mapping) and str(row.get("receipt_id", "")).strip()
                }
            )
    except ReverseSurfaceOwnerAuthorityError:
        prior_receipt_ids = []
    receipt_inventory: tuple[EvidenceReceipt, ...] = ()
    if prior_receipt_ids:
        try:
            from .evidence_receipts import list_evidence_receipts

            receipt_inventory = list_evidence_receipts(
                root_path,
                output_directory=receipt_root,
                receipt_ids=prior_receipt_ids,
            )
        except Exception:
            # A stale/corrupt prior authority is not current evidence.  The
            # current owner will publish a new receipt below and its failure
            # remains visible through normal verification.
            receipt_inventory = ()
    now = datetime.now(timezone.utc).isoformat()
    for contract in contracts:
        model_ids = bindings[contract.owner_id]
        current = build_owner_current(root_path, contract, all_contracts=all_contracts)
        child_receipts_for_route = tuple(child_receipts[model_id] for model_id in model_ids)
        child_verifications_for_route = tuple(
            parent.verifications_by_model[model_id] for model_id in model_ids
        )
        receipt, verification = find_reusable_owner_receipt(
            current,
            root_path,
            receipt_root,
            receipt_inventory=receipt_inventory,
            child_receipts=child_receipts_for_route,
            child_verification_results=child_verifications_for_route,
        )
        if receipt is not None:
            # ``find_reusable_owner_receipt`` verifies the ordinary owner
            # contract.  Recheck the composed child proof before accepting it
            # as the persistent reverse authority output.
            composed_context = build_child_bound_owner_receipt_context(
                current,
                receipt,
                root_path,
                receipt_root,
                child_receipts=child_receipts_for_route,
                child_verification_results=child_verifications_for_route,
                receipt_store_receipt_ids=(
                    receipt.receipt_id,
                    *(item.receipt_id for item in child_receipts_for_route),
                ),
            )
            composed_verification = verify_evidence_receipt(receipt, composed_context)
            if not composed_verification.ok:
                receipt = None
                verification = None
            else:
                verification = composed_verification
        if receipt is None or verification is None or not verification.ok:
            receipt, verification = save_child_bound_owner_receipt(
                current,
                child_receipts_for_route,
                root_path,
                receipt_root,
                all_contracts=all_contracts,
                child_contracts=tuple(
                    parent.contracts_by_model[model_id] for model_id in model_ids
                ),
                started_at=now,
                finished_at=now,
                evidence_context={
                    "authority_identity": dict(authority_identity),
                    "discovery_fingerprint": discovery_fingerprint,
                    "discovered_surface_count": discovered_surface_count,
                    "owner_route": contract.owner_id,
                    "model_ids": list(model_ids),
                    "model_parent_receipt_fingerprint": parent_fingerprint,
                    "route_set_fingerprint": route_set_fingerprint,
                    "owner_bindings_fingerprint": bindings_fingerprint,
                    "semantic_map_fingerprint": semantic_map_fingerprint,
                },
                claim_boundary=(
                    "Persistent reverse-surface owner authority for one exact current "
                    "owner route, composed from exact-current model-regression leaf "
                    "receipts and the current source discovery identity. It does not "
                    "replace revision affected-closure evidence."
                ),
            )
        if not verification.ok:
            raise ReverseSurfaceOwnerAuthorityError(
                f"published reverse owner receipt is not current: {contract.owner_id}"
            )
        published.append(
            {
                "owner_route": contract.owner_id,
                "model_ids": list(model_ids),
                "receipt_id": receipt.receipt_id,
                "receipt_fingerprint": receipt.fingerprint,
                "subject_fingerprint": authority_identity["snapshot_fingerprint"],
                "candidate_snapshot_fingerprint": authority_identity["snapshot_fingerprint"],
                "owner_identity": current.owner_identity,
                "receipt_ref": _receipt_path(
                    root_path,
                    receipt,
                    receipt_root=receipt_root,
                ),
                "contract": contract.to_dict(),
            }
        )
    body = {
        "schema_version": REVERSE_SURFACE_OWNER_AUTHORITY_SCHEMA,
        "status": "current",
        "authority_identity": authority_identity,
        "discovery_fingerprint": discovery_fingerprint,
        "discovered_surface_count": discovered_surface_count,
        "owner_bindings_fingerprint": bindings_fingerprint,
        "route_set_fingerprint": route_set_fingerprint,
        "semantic_map_fingerprint": semantic_map_fingerprint,
        "owner_routes": route_rows,
        "model_parent_receipt_path": _relative_path(root_path, parent_path),
        "model_parent_receipt_fingerprint": parent_fingerprint,
        "owner_receipt_identities": published,
        "claim_boundary": (
            "Complete current persistent reverse-surface owner receipt denominator; "
            "it is independent of delta-local revision evidence and has no fallback "
            "or legacy reader."
        ),
        "no_fallback_policy": "missing or stale current owner evidence blocks direct-current reverse closure",
    }
    artifact = {**body, "artifact_fingerprint": _canonical_hash(body)}
    _write_json(root_path / REVERSE_SURFACE_OWNER_AUTHORITY_RELATIVE_PATH, artifact)
    return artifact


def load_current_reverse_surface_owner_authority(
    root: str | Path,
    *,
    authority_identity: Mapping[str, str],
) -> dict[str, Any]:
    """Load and independently verify the current persistent reverse authority."""

    root_path = Path(root).resolve()
    path = root_path / REVERSE_SURFACE_OWNER_AUTHORITY_RELATIVE_PATH
    payload = _read_json(path)
    if not isinstance(payload, Mapping):
        raise ReverseSurfaceOwnerAuthorityError("current reverse owner authority must be an object")
    required = {
        "schema_version", "status", "authority_identity", "discovery_fingerprint",
        "discovered_surface_count", "owner_bindings_fingerprint", "route_set_fingerprint",
        "semantic_map_fingerprint",
        "owner_routes", "model_parent_receipt_path", "model_parent_receipt_fingerprint",
        "owner_receipt_identities", "claim_boundary", "no_fallback_policy", "artifact_fingerprint",
    }
    if set(payload) != required:
        raise ReverseSurfaceOwnerAuthorityError(
            "current reverse owner authority fields are not exact"
        )
    body = {key: payload[key] for key in required if key != "artifact_fingerprint"}
    if payload["artifact_fingerprint"] != _canonical_hash(body):
        raise ReverseSurfaceOwnerAuthorityError("current reverse owner authority fingerprint is stale")
    if payload["schema_version"] != REVERSE_SURFACE_OWNER_AUTHORITY_SCHEMA or payload["status"] != "current":
        raise ReverseSurfaceOwnerAuthorityError("current reverse owner authority schema/status is not current")
    if dict(payload["authority_identity"]) != dict(authority_identity):
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority is bound to a different current model authority")
    discovery_fingerprint, discovered_count = _load_current_discovery(root_path)
    if payload["discovery_fingerprint"] != discovery_fingerprint or int(payload["discovered_surface_count"]) != discovered_count:
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority discovery identity is stale")
    bindings, bindings_fingerprint = _load_owner_bindings(root_path)
    if payload["owner_bindings_fingerprint"] != bindings_fingerprint:
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority owner-bindings identity is stale")
    semantic_map_fingerprint = _semantic_map_binding_fingerprint(root_path)
    if payload["semantic_map_fingerprint"] != semantic_map_fingerprint:
        raise ReverseSurfaceOwnerAuthorityError(
            "reverse owner authority semantic-map identity is stale"
        )
    routes = tuple(
        (str(row.get("owner_route", "")).strip(), tuple(sorted(str(item).strip() for item in row.get("model_ids", ()))))
        for row in payload["owner_routes"]
        if isinstance(row, Mapping)
    )
    if not routes or len({route for route, _models in routes}) != len(routes):
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority route denominator is invalid")
    expected_routes = tuple(sorted((route, bindings[route]) for route, _models in routes if route in bindings))
    if expected_routes != routes:
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority route/model bindings are stale")
    route_rows = [{"owner_route": route, "model_ids": list(models)} for route, models in routes]
    if payload["route_set_fingerprint"] != _canonical_hash(route_rows):
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority route-set fingerprint is stale")
    parent_path = (root_path / str(payload["model_parent_receipt_path"])).resolve()
    if root_path not in parent_path.parents or not parent_path.is_file():
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority model parent path is invalid")
    receipt_root = _receipt_root_for_parent(root_path, parent_path)
    parent = _parent_for_current(
        root_path,
        parent_path,
        receipt_root=receipt_root,
    )
    if parent.fingerprint != payload["model_parent_receipt_fingerprint"]:
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority model parent is stale")
    rows = payload["owner_receipt_identities"]
    if not isinstance(rows, list) or len(rows) != len(routes):
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority receipt denominator is not exact")
    child_models = {
        model_id
        for _route, models in routes
        for model_id in models
    }
    child_contracts = tuple(parent.contracts_by_model[model_id] for model_id in sorted(child_models))
    child_receipts = {model_id: parent.receipts_by_model[model_id] for model_id in sorted(child_models)}
    contracts = tuple(
        build_reverse_owner_contract(
            route=route,
            model_ids=models,
            authority_identity=authority_identity,
            discovery_fingerprint=discovery_fingerprint,
            owner_bindings_fingerprint=bindings_fingerprint,
            route_set_fingerprint=payload["route_set_fingerprint"],
            model_parent_fingerprint=parent.fingerprint,
            semantic_map_fingerprint=semantic_map_fingerprint,
            child_receipts=child_receipts,
        )
        for route, models in routes
    )
    all_contracts = tuple([*child_contracts, *contracts])
    by_route = {str(row.get("owner_route", "")): row for row in rows if isinstance(row, Mapping)}
    if set(by_route) != {route for route, _models in routes}:
        raise ReverseSurfaceOwnerAuthorityError("reverse owner authority receipt routes are not exact")
    identities: list[dict[str, str]] = []
    for contract in contracts:
        row = by_route[contract.owner_id]
        model_ids = dict(routes)[contract.owner_id]
        expected = build_owner_current(root_path, contract, all_contracts=all_contracts)
        try:
            receipt = load_evidence_receipt(
                str(row.get("receipt_id", "")),
                root_path,
                output_directory=receipt_root,
            )
        except (OSError, ValueError) as exc:
            raise ReverseSurfaceOwnerAuthorityError(
                f"current reverse owner receipt is unavailable: {contract.owner_id}: {exc}"
            ) from exc
        if receipt.fingerprint != str(row.get("receipt_fingerprint", "")):
            raise ReverseSurfaceOwnerAuthorityError(
                f"current reverse owner receipt fingerprint mismatch: {contract.owner_id}"
            )
        if (
            receipt.subject_id != f"validation-owner:{contract.owner_id}"
            or receipt.subject_kind != OWNER_RECEIPT_KIND
            or receipt.producer_id != receipt.subject_id
            or receipt.claim_scope != OWNER_RECEIPT_SCOPE
            or receipt.result_status != RECEIPT_STATUS_PASS
            or receipt.exit_code != 0
            or receipt.covered_obligations != contract.obligation_ids
            or receipt.skipped_checks
            or receipt.blockers
            or str(row.get("owner_identity", "")) != expected.owner_identity
            or str(row.get("candidate_snapshot_fingerprint", "")) != authority_identity["snapshot_fingerprint"]
        ):
            raise ReverseSurfaceOwnerAuthorityError(
                f"current reverse owner receipt identity is not exact: {contract.owner_id}"
            )
        child_receipt_values = tuple(child_receipts[model_id] for model_id in model_ids)
        child_verifications = tuple(parent.verifications_by_model[model_id] for model_id in model_ids)
        context = build_child_bound_owner_receipt_context(
            expected,
            receipt,
            root_path,
            receipt_root,
            child_receipts=child_receipt_values,
            child_verification_results=child_verifications,
        )
        verification = verify_evidence_receipt(receipt, context)
        if not verification.ok:
            raise ReverseSurfaceOwnerAuthorityError(
                f"current reverse owner receipt failed fresh verification: {contract.owner_id}"
            )
        identities.append(
            {
                "owner_route": contract.owner_id,
                "receipt_id": receipt.receipt_id,
                "receipt_fingerprint": receipt.fingerprint,
                "subject_fingerprint": authority_identity["snapshot_fingerprint"],
                "candidate_snapshot_fingerprint": authority_identity["snapshot_fingerprint"],
            }
        )
    return {
        "schema_version": REVERSE_SURFACE_OWNER_AUTHORITY_SCHEMA,
        "status": "current",
        "authority_artifact_fingerprint": str(payload["artifact_fingerprint"]),
        "owner_receipt_identities": sorted(
            identities,
            key=lambda item: (item["owner_route"], item["receipt_id"]),
        ),
        "owner_routes": route_rows,
        "discovery_fingerprint": discovery_fingerprint,
        "discovered_surface_count": discovered_count,
        "semantic_map_fingerprint": semantic_map_fingerprint,
    }


__all__ = [
    "REVERSE_SURFACE_OWNER_AUTHORITY_SCHEMA",
    "REVERSE_SURFACE_OWNER_AUTHORITY_RELATIVE_PATH",
    "ReverseSurfaceOwnerAuthorityError",
    "build_current_reverse_surface_owner_authority",
    "build_reverse_owner_contract",
    "load_current_reverse_surface_owner_authority",
]
