"""Taxonomy axes for the real software problem corpus.

These axes describe real software problem space only. They intentionally do not
assign cases to roadmap phases or current flowguard capability levels.
"""

from __future__ import annotations


SOFTWARE_DOMAINS = (
    "backend_service",
    "desktop_application",
    "web_application",
    "data_pipeline",
    "agent_workflow",
    "commerce_system",
    "identity_access",
    "messaging_system",
    "document_system",
    "operations_platform",
    "compliance_system",
    "integration_service",
)


WORKFLOW_FAMILIES = (
    {
        "name": "crud_lifecycle",
        "domain": "backend_service",
        "structure": "controller -> validator -> repository -> audit log",
        "boundary": "create/update/delete entity lifecycle",
        "actors": ("user", "api_handler", "repository"),
        "side_effects": ("entity_record", "audit_log"),
    },
    {
        "name": "approval_review_workflow",
        "domain": "web_application",
        "structure": "submitter -> reviewer -> approval state -> notification",
        "boundary": "submit item for approval and finalize review",
        "actors": ("submitter", "reviewer", "workflow_service"),
        "side_effects": ("approval_record", "review_notification"),
    },
    {
        "name": "task_queue_leasing",
        "domain": "operations_platform",
        "structure": "queue -> lease manager -> worker -> completion registry",
        "boundary": "lease task, process task, complete or retry",
        "actors": ("worker", "lease_manager", "queue"),
        "side_effects": ("task_lease", "completion_record"),
    },
    {
        "name": "retry_side_effect",
        "domain": "backend_service",
        "structure": "request handler -> idempotency store -> side-effect sender",
        "boundary": "retry request after partial side effect",
        "actors": ("client", "handler", "external_service"),
        "side_effects": ("send_log", "idempotency_record"),
    },
    {
        "name": "cache_materialized_view",
        "domain": "data_pipeline",
        "structure": "source of truth -> cache -> derived view -> reader",
        "boundary": "read derived value after source or cache change",
        "actors": ("reader", "cache", "source_store"),
        "side_effects": ("cache_entry", "materialized_view"),
    },
    {
        "name": "file_import_transform_export",
        "domain": "data_pipeline",
        "structure": "file watcher -> parser -> transformer -> output writer",
        "boundary": "import file, transform rows, write output",
        "actors": ("file_watcher", "parser", "writer"),
        "side_effects": ("output_file", "processing_record"),
    },
    {
        "name": "event_webhook_ingestion",
        "domain": "integration_service",
        "structure": "webhook receiver -> dedup store -> event applier",
        "boundary": "receive external event and apply state change",
        "actors": ("webhook_sender", "receiver", "event_store"),
        "side_effects": ("event_record", "domain_update"),
    },
    {
        "name": "notification_send_pipeline",
        "domain": "messaging_system",
        "structure": "decision -> template renderer -> send adapter -> delivery log",
        "boundary": "decide and send one notification",
        "actors": ("scheduler", "renderer", "send_adapter"),
        "side_effects": ("delivery_log", "notification_record"),
    },
    {
        "name": "payment_billing_refund",
        "domain": "commerce_system",
        "structure": "invoice -> charge -> ledger -> refund processor",
        "boundary": "charge, settle, refund, and record ledger movement",
        "actors": ("customer", "payment_gateway", "ledger"),
        "side_effects": ("charge_record", "ledger_entry", "refund_record"),
    },
    {
        "name": "inventory_reservation_allocation",
        "domain": "commerce_system",
        "structure": "availability -> reservation -> allocation -> release",
        "boundary": "reserve stock and convert or release reservation",
        "actors": ("buyer", "inventory_service", "allocator"),
        "side_effects": ("reservation_record", "stock_count"),
    },
    {
        "name": "scheduler_recurring_job",
        "domain": "operations_platform",
        "structure": "cron trigger -> run registry -> job worker -> status store",
        "boundary": "trigger recurring job and settle run status",
        "actors": ("scheduler", "job_worker", "status_store"),
        "side_effects": ("run_record", "job_output"),
    },
    {
        "name": "auth_permission_role_transition",
        "domain": "identity_access",
        "structure": "identity store -> policy evaluator -> permission cache",
        "boundary": "evaluate permission after role transition",
        "actors": ("user", "policy_engine", "resource"),
        "side_effects": ("permission_decision", "policy_audit"),
    },
    {
        "name": "session_token_expiration",
        "domain": "identity_access",
        "structure": "session store -> token validator -> resource action",
        "boundary": "validate token and allow or reject action",
        "actors": ("client", "token_validator", "resource_service"),
        "side_effects": ("session_record", "access_audit"),
    },
    {
        "name": "form_submission_validation",
        "domain": "web_application",
        "structure": "form submit -> validator -> draft/save -> confirmation",
        "boundary": "submit form and persist accepted data",
        "actors": ("user", "validator", "form_store"),
        "side_effects": ("form_record", "confirmation"),
    },
    {
        "name": "search_ranking_recommendation",
        "domain": "agent_workflow",
        "structure": "candidate source -> scorer -> ranker -> recommendation record",
        "boundary": "score item and decide recommendation",
        "actors": ("source", "scorer", "ranker"),
        "side_effects": ("score_record", "recommendation_record"),
    },
    {
        "name": "data_sync_reconciliation",
        "domain": "integration_service",
        "structure": "remote snapshot -> local state -> reconciliation engine",
        "boundary": "sync remote changes into local source of truth",
        "actors": ("remote_system", "sync_worker", "local_store"),
        "side_effects": ("sync_record", "local_update"),
    },
    {
        "name": "migration_schema_evolution",
        "domain": "operations_platform",
        "structure": "old schema -> migrator -> new schema -> compatibility reader",
        "boundary": "migrate persisted state and keep compatibility",
        "actors": ("migrator", "reader", "operator"),
        "side_effects": ("schema_version_record", "migrated_record"),
    },
    {
        "name": "human_in_the_loop_workflow",
        "domain": "agent_workflow",
        "structure": "automated decision -> human review queue -> final action",
        "boundary": "route uncertain result to human review",
        "actors": ("agent", "human_reviewer", "decision_store"),
        "side_effects": ("review_task", "final_decision"),
    },
    {
        "name": "moderation_triage",
        "domain": "compliance_system",
        "structure": "content ingest -> classifier -> moderation queue -> action",
        "boundary": "triage content and apply moderation decision",
        "actors": ("content_source", "moderator", "policy_engine"),
        "side_effects": ("moderation_record", "content_action"),
    },
    {
        "name": "classifier_decision_routing_no_api",
        "domain": "agent_workflow",
        "structure": "abstract classifier output -> router -> downstream handler",
        "boundary": "route uncertain classifier category without calling an API",
        "actors": ("classifier_model", "router", "handler"),
        "side_effects": ("routing_record", "handler_result"),
    },
    {
        "name": "document_generation_export",
        "domain": "document_system",
        "structure": "source data -> renderer -> export writer -> index",
        "boundary": "generate and export a document artifact",
        "actors": ("renderer", "exporter", "indexer"),
        "side_effects": ("document_file", "index_record"),
    },
    {
        "name": "checkout_onboarding_flow",
        "domain": "commerce_system",
        "structure": "step state -> validator -> payment/profile -> completion",
        "boundary": "advance multi-step checkout or onboarding flow",
        "actors": ("user", "step_controller", "profile_store"),
        "side_effects": ("step_record", "completion_record"),
    },
    {
        "name": "audit_compliance_traceability",
        "domain": "compliance_system",
        "structure": "business action -> audit event -> immutable ledger",
        "boundary": "perform action and record traceable audit evidence",
        "actors": ("actor", "business_service", "audit_sink"),
        "side_effects": ("audit_event", "business_record"),
    },
    {
        "name": "deployment_release_gate",
        "domain": "operations_platform",
        "structure": "build artifact -> gate checks -> rollout state -> rollback",
        "boundary": "promote or block deployment artifact",
        "actors": ("release_manager", "gate_checker", "rollout_controller"),
        "side_effects": ("release_record", "deployment_state"),
    },
    {
        "name": "configuration_feature_flag_rollout",
        "domain": "operations_platform",
        "structure": "flag config -> validator -> rollout segment -> reader cache",
        "boundary": "update feature flag and expose it to readers",
        "actors": ("operator", "config_service", "reader"),
        "side_effects": ("config_record", "rollout_record"),
    },
)


INPUT_PATTERNS = (
    "single_valid_input",
    "repeated_identical_input",
    "same_input_three_times",
    "a_b_a_repeated_input",
    "a_b_b_a_interleaving",
    "duplicate_request_same_idempotency_key",
    "duplicate_request_different_idempotency_key",
    "out_of_order_events",
    "missing_required_field",
    "malformed_field",
    "unknown_enum_category",
    "conflicting_same_identity_payload",
    "stale_version_input",
    "deterministic_concurrent_interleaving",
    "empty_input_sequence",
    "terminal_state_input",
    "retry_after_partial_success",
    "replayed_webhook",
    "batched_mixed_validity_input",
    "boundary_numeric_or_date_value",
    "expired_credential_or_session",
    "user_correction_after_previous_decision",
)


STATE_PATTERNS = (
    "empty_state",
    "already_processed",
    "partially_processed",
    "cached_but_source_missing",
    "source_updated_cache_stale",
    "terminal_success",
    "terminal_failure",
    "waiting_or_pending",
    "leased_or_locked",
    "expired_lease",
    "dirty_derived_state",
    "duplicate_existing_records",
    "conflicting_existing_records",
    "missing_owner_marker",
    "wrong_owner_marker",
    "orphaned_side_effect",
    "pending_human_review",
    "invalid_initial_state",
    "migrated_old_version_state",
    "rollback_or_compensation_needed",
)


FAILURE_MODES = (
    "duplicate_side_effect",
    "missing_idempotency",
    "repeated_processing_without_refresh",
    "stale_cache",
    "cache_source_mismatch",
    "missing_source_traceability",
    "write_without_validated_source",
    "wrong_state_owner",
    "forbidden_state_mutation",
    "missing_decision",
    "contradictory_decision",
    "duplicate_decision",
    "dropped_unknown_category",
    "unhandled_branch",
    "invalid_transition_accepted",
    "valid_transition_rejected",
    "terminal_state_mutated",
    "nonterminal_dead_end",
    "closed_loop",
    "loop_with_no_modeled_progress",
    "unreachable_success",
    "retry_forever",
    "retry_after_terminal_failure",
    "send_before_idempotency_key",
    "complete_without_lease",
    "double_lease",
    "reservation_oversell",
    "refund_without_charge",
    "permission_bypass",
    "stale_permission_decision",
    "token_reuse_after_expiry",
    "partial_commit",
    "orphaned_side_effect",
    "cleanup_deletes_live_data",
    "migration_loses_data",
    "projection_hides_bug",
    "adapter_normalizes_away_violation",
    "downstream_non_consumable_output",
    "schema_version_mismatch",
    "ordering_sensitive_transition",
    "conflict_policy_missing",
    "human_review_bypass",
    "audit_log_missing_or_inconsistent",
)


ORACLE_TYPES = (
    "invariant_oracle",
    "exact_final_state_oracle",
    "allowed_transition_oracle",
    "forbidden_transition_oracle",
    "required_label_oracle",
    "forbidden_label_oracle",
    "side_effect_count_oracle",
    "traceability_oracle",
    "idempotency_oracle",
    "terminal_semantics_oracle",
    "reachability_oracle",
    "loop_stuck_oracle",
    "conformance_projection_oracle",
    "custom_scenario_oracle",
    "human_review_oracle",
    "known_limitation_oracle",
    "metamorphic_repeat_input_oracle",
    "downstream_compatibility_oracle",
    "temporal_obligation_oracle",
    "refinement_projection_oracle",
    "artifact_stability_oracle",
)


GAP_FOCUS_AREAS = (
    {
        "name": "identity_merge_split_conflict",
        "quota": 60,
        "domain": "identity_access",
        "description": "Same logical identity appears through merge, split, rename, tombstone, or conflicting payloads.",
        "inputs": (
            "same_identity_conflicting_payload",
            "merge_request_after_independent_updates",
            "split_request_after_shared_side_effect",
            "rename_event_then_replayed_old_name",
            "delete_then_recreate_same_identity",
        ),
        "states": (
            "two_records_share_identity_key",
            "identity_has_tombstone_and_live_record",
            "normalized_id_conflicts_with_source_id",
            "merged_identity_has_unmerged_side_effects",
            "identity_alias_points_to_stale_record",
        ),
        "failure_modes": (
            "identity_conflict_policy_missing",
            "merge_duplicates_side_effects",
            "split_loses_source_trace",
            "tombstoned_identity_reactivated_silently",
            "alias_resolution_uses_wrong_record",
        ),
        "oracles": (
            "identity_consistency_oracle",
            "traceability_oracle",
            "side_effect_count_oracle",
            "custom_scenario_oracle",
        ),
        "evidence_focus": "identity lineage, alias resolution, tombstone handling, and per-identity side-effect counts",
    },
    {
        "name": "partial_failure_atomicity_compensation",
        "quota": 70,
        "domain": "backend_service",
        "description": "Workflow succeeds in one subsystem and fails in another, requiring explicit atomicity or compensation.",
        "inputs": (
            "retry_after_external_success_local_failure",
            "compensation_request_after_partial_commit",
            "rollback_after_downstream_timeout",
            "duplicate_retry_after_compensation",
            "operator_repair_after_half_written_state",
        ),
        "states": (
            "external_side_effect_without_local_record",
            "local_record_without_external_confirmation",
            "compensation_pending",
            "rollback_applied_but_derived_state_dirty",
            "partial_commit_crosses_module_boundary",
        ),
        "failure_modes": (
            "partial_commit_not_detected",
            "compensation_replayed_twice",
            "rollback_drops_source_trace",
            "external_success_retried_as_new_action",
            "local_repair_creates_second_source_of_truth",
        ),
        "oracles": (
            "atomicity_oracle",
            "compensation_oracle",
            "idempotency_oracle",
            "traceability_oracle",
        ),
        "evidence_focus": "partial writes, compensation records, retry labels, and source trace continuity",
    },
    {
        "name": "ordering_race_duplicate_delivery",
        "quota": 70,
        "domain": "integration_service",
        "description": "Inputs arrive out of order, concurrently, or more than once under deterministic interleavings.",
        "inputs": (
            "complete_before_start_event",
            "cancel_and_apply_interleaving",
            "duplicate_delivery_with_new_timestamp",
            "out_of_order_version_sequence",
            "concurrent_terminal_updates",
        ),
        "states": (
            "latest_version_already_applied",
            "terminal_state_with_pending_event",
            "lease_missing_but_completion_arrived",
            "two_workers_claim_same_object",
            "event_offset_gap_detected",
        ),
        "failure_modes": (
            "out_of_order_event_regresses_state",
            "duplicate_delivery_replays_side_effect",
            "concurrent_terminal_conflict",
            "late_cancel_overwrites_success",
            "event_gap_silently_accepted",
        ),
        "oracles": (
            "ordering_oracle",
            "terminal_semantics_oracle",
            "side_effect_count_oracle",
            "forbidden_transition_oracle",
        ),
        "evidence_focus": "event order, terminal transition history, duplicate delivery keys, and deterministic interleavings",
    },
    {
        "name": "permission_ownership_boundary",
        "quota": 50,
        "domain": "identity_access",
        "description": "Authority, ownership, and module write boundaries change while workflow state is active.",
        "inputs": (
            "role_downgrade_after_permission_cache",
            "admin_override_without_audit",
            "read_only_action_attempts_write",
            "owner_transfer_then_old_owner_updates",
            "service_account_cross_boundary_write",
        ),
        "states": (
            "permission_cache_stale_after_role_change",
            "resource_owner_changed",
            "write_scope_missing",
            "audit_required_but_absent",
            "policy_version_mismatch",
        ),
        "failure_modes": (
            "stale_authorization_allows_write",
            "owner_boundary_bypass",
            "read_only_flow_mutates_state",
            "override_missing_audit_record",
            "policy_cache_masks_denial",
        ),
        "oracles": (
            "permission_oracle",
            "ownership_oracle",
            "forbidden_transition_oracle",
            "traceability_oracle",
        ),
        "evidence_focus": "actor permissions, owner markers, forbidden writes, and audit records",
    },
    {
        "name": "time_expiry_scheduling",
        "quota": 50,
        "domain": "operations_platform",
        "description": "Expiry, scheduling boundaries, and delayed inputs affect whether a transition remains legal.",
        "inputs": (
            "expired_token_reused",
            "scheduled_job_fires_twice",
            "delayed_event_after_terminal",
            "day_boundary_retry",
            "lease_expiry_then_completion",
        ),
        "states": (
            "expired_session_still_cached",
            "run_window_already_closed",
            "terminal_state_before_delayed_event",
            "lease_expired_but_worker_active",
            "timezone_boundary_state",
        ),
        "failure_modes": (
            "expired_authority_reused",
            "scheduler_double_fire",
            "delayed_event_mutates_terminal_state",
            "retry_window_ignored",
            "lease_expiry_not_enforced",
        ),
        "oracles": (
            "time_window_oracle",
            "terminal_semantics_oracle",
            "side_effect_count_oracle",
            "forbidden_transition_oracle",
        ),
        "evidence_focus": "expiry state, scheduled run identity, retry window, and terminal mutation evidence",
    },
    {
        "name": "sync_reconciliation_source_of_truth",
        "quota": 60,
        "domain": "integration_service",
        "description": "Multiple replicas, caches, or sources disagree during reconciliation.",
        "inputs": (
            "remote_snapshot_older_than_local",
            "source_delete_with_cached_derived_output",
            "reconciliation_replays_old_change",
            "two_sources_claim_authority",
            "stale_replica_overwrites_new_value",
        ),
        "states": (
            "local_newer_than_remote",
            "source_deleted_cache_present",
            "derived_output_without_source",
            "conflicting_source_versions",
            "sync_checkpoint_behind_applied_state",
        ),
        "failure_modes": (
            "stale_replica_overwrites_source",
            "deleted_source_still_outputs_downstream",
            "reconciliation_duplicates_record",
            "second_source_of_truth_created",
            "sync_checkpoint_regresses_state",
        ),
        "oracles": (
            "source_of_truth_oracle",
            "traceability_oracle",
            "cache_consistency_oracle",
            "side_effect_count_oracle",
        ),
        "evidence_focus": "source version, cache entry, derived output source, and reconciliation checkpoint",
    },
    {
        "name": "schema_migration_version_compatibility",
        "quota": 50,
        "domain": "data_pipeline",
        "description": "Old and new schema versions coexist while workflows still need deterministic routing.",
        "inputs": (
            "old_schema_event_without_new_default",
            "new_schema_event_to_old_consumer",
            "backfill_reprocesses_migrated_record",
            "migration_resume_after_partial_batch",
            "compat_reader_sees_mixed_versions",
        ),
        "states": (
            "mixed_schema_versions_present",
            "default_value_missing",
            "migration_checkpoint_partial",
            "old_consumer_cached_schema",
            "backfill_output_already_written",
        ),
        "failure_modes": (
            "schema_default_missing_changes_decision",
            "old_consumer_cannot_process_new_output",
            "backfill_duplicates_side_effect",
            "migration_resume_skips_record",
            "compatibility_reader_uses_wrong_version",
        ),
        "oracles": (
            "schema_compatibility_oracle",
            "downstream_compatibility_oracle",
            "traceability_oracle",
            "idempotency_oracle",
        ),
        "evidence_focus": "schema version, compatibility branch, migration checkpoint, and downstream consumability",
    },
    {
        "name": "audit_privacy_compliance_traceability",
        "quota": 40,
        "domain": "compliance_system",
        "description": "Traceability, privacy deletion, and audit obligations must survive retries and overrides.",
        "inputs": (
            "privacy_delete_after_cached_output",
            "human_override_without_reason",
            "audit_sink_failure_after_business_action",
            "redaction_request_during_export",
            "compliance_replay_after_policy_change",
        ),
        "states": (
            "audit_log_missing_business_action",
            "pii_cached_after_delete_request",
            "override_reason_absent",
            "export_contains_unredacted_field",
            "policy_version_changed_since_action",
        ),
        "failure_modes": (
            "privacy_delete_not_propagated",
            "audit_log_missing_after_side_effect",
            "override_without_reason_trace",
            "redaction_applied_after_export",
            "policy_replay_uses_current_rule_for_old_action",
        ),
        "oracles": (
            "compliance_traceability_oracle",
            "privacy_propagation_oracle",
            "audit_consistency_oracle",
            "human_review_oracle",
        ),
        "evidence_focus": "audit entry, privacy tombstone, redaction state, and override reason",
    },
    {
        "name": "external_integration_ack_idempotency",
        "quota": 50,
        "domain": "integration_service",
        "description": "External systems acknowledge, time out, replay, or disagree with local workflow state.",
        "inputs": (
            "external_ack_lost_then_retry",
            "third_party_webhook_replayed_after_success",
            "idempotency_key_reused_across_resource",
            "external_timeout_after_side_effect",
            "provider_sends_conflicting_status",
        ),
        "states": (
            "external_done_local_unknown",
            "local_done_external_unknown",
            "idempotency_key_scope_ambiguous",
            "provider_status_conflicts_with_ledger",
            "webhook_seen_but_action_not_recorded",
        ),
        "failure_modes": (
            "lost_ack_causes_duplicate_external_action",
            "webhook_replay_mutates_terminal_state",
            "idempotency_key_scope_leak",
            "external_timeout_retried_without_observation",
            "provider_conflict_silently_accepted",
        ),
        "oracles": (
            "external_observation_oracle",
            "idempotency_oracle",
            "conformance_projection_oracle",
            "terminal_semantics_oracle",
        ),
        "evidence_focus": "external acknowledgement, local observation, idempotency scope, and provider conflict handling",
    },
)


PRESSURE_FOCUS_AREAS = (
    {
        "name": "bounded_progress_and_fairness",
        "quota": 25,
        "domain": "operations_platform",
        "description": "Cycles with an escape path but no modeled guarantee that progress must be taken.",
        "input_pattern": "cycle_with_escape_edge",
        "state_pattern": "cycle_state_has_no_ranking_progress",
        "failure_mode": "cycle_with_escape_without_forced_progress",
        "oracle_type": "known_limitation_oracle",
        "case_kind": "loop_or_stuck_case",
        "evidence_focus": "cycle edge, escape edge, missing ranking progress, and explicit limitation status",
        "expected_status": "known_limitation",
    },
    {
        "name": "eventual_obligation_and_temporal_order",
        "quota": 25,
        "domain": "backend_service",
        "description": "A side effect creates an obligation that should eventually reach a terminal decision.",
        "input_pattern": "effect_then_missing_eventual_decision",
        "state_pattern": "side_effect_pending_without_terminal_followup",
        "failure_mode": "record_without_eventual_decision",
        "oracle_type": "temporal_obligation_oracle",
        "case_kind": "negative_broken_case",
        "evidence_focus": "side effect identity, missing final decision, and expected eventually obligation",
        "expected_status": "violation",
    },
    {
        "name": "contract_composition_refinement",
        "quota": 25,
        "domain": "integration_service",
        "description": "A function output, state write, or production projection violates the intended abstract contract.",
        "input_pattern": "contract_boundary_output_projection",
        "state_pattern": "raw_state_diverges_from_projected_state",
        "failure_mode": "projection_refinement_hides_raw_violation",
        "oracle_type": "refinement_projection_oracle",
        "case_kind": "negative_broken_case",
        "evidence_focus": "raw observed state, projected state, forbidden write, and output-input compatibility",
        "expected_status": "violation",
    },
    {
        "name": "benchmark_freeze_and_artifact_stability",
        "quota": 25,
        "domain": "operations_platform",
        "description": "Benchmark artifacts must preserve expected-vs-observed status, limitation labels, and schema fields.",
        "input_pattern": "baseline_artifact_replay_after_tool_change",
        "state_pattern": "stored_report_schema_with_known_limitation",
        "failure_mode": "benchmark_artifact_silently_relabels_limitation",
        "oracle_type": "artifact_stability_oracle",
        "case_kind": "boundary_edge_case",
        "evidence_focus": "stable report fields, explicit limitation status, deterministic serialization, and no silent relabeling",
        "expected_status": "ok",
    },
)


CASE_KIND_QUOTAS = (
    ("positive_correct_case", 12),
    ("negative_broken_case", 20),
    ("boundary_edge_case", 12),
    ("invalid_initial_state_case", 8),
    ("loop_or_stuck_case", 8),
)


IMPORTANCE_LEVELS = ("medium", "high", "critical")


__all__ = [
    "CASE_KIND_QUOTAS",
    "FAILURE_MODES",
    "GAP_FOCUS_AREAS",
    "IMPORTANCE_LEVELS",
    "INPUT_PATTERNS",
    "ORACLE_TYPES",
    "PRESSURE_FOCUS_AREAS",
    "SOFTWARE_DOMAINS",
    "STATE_PATTERNS",
    "WORKFLOW_FAMILIES",
]
