"""FlowGuard DevelopmentProcessFlow model for the v0.18.4 prompt release.

Purpose: review the lifecycle from OpenSpec requirement updates through local
FlowGuard modeling, skill/doc edits, validation, install sync, shadow workspace
sync, git tag, and GitHub release.
"""

from __future__ import annotations

from flowguard import (
    PROCESS_ARTIFACT_CODE,
    PROCESS_ARTIFACT_DOC,
    PROCESS_ARTIFACT_MODEL,
    PROCESS_ARTIFACT_RELEASE,
    PROCESS_ARTIFACT_REQUIREMENT,
    PROCESS_ARTIFACT_TEST,
    PROCESS_EVIDENCE_PASSED,
    PROCESS_SCOPE_RELEASE,
    DevelopmentProcessPlan,
    FreshnessRule,
    ProcessAction,
    ProcessArtifact,
    ProcessEvidence,
    ValidationRequirement,
    review_development_process_flow,
)


def release_artifacts(
    *,
    requirements_version: str = "2",
    model_version: str = "2",
    prompt_version: str = "2",
    docs_version: str = "2",
    tests_version: str = "2",
    install_version: str = "2",
    shadow_version: str = "2",
    git_version: str = "2",
    release_version: str = "2",
):
    return (
        ProcessArtifact(
            "openspec.requirements",
            PROCESS_ARTIFACT_REQUIREMENT,
            requirements_version,
            path="openspec/changes/*",
            description="OpenSpec changes for global routing and model visibility.",
        ),
        ProcessArtifact(
            "flowguard.models",
            PROCESS_ARTIFACT_MODEL,
            model_version,
            path=".flowguard/*",
            upstream_artifact_ids=("openspec.requirements",),
            description="Executable local FlowGuard models for prompt behavior and release lifecycle.",
        ),
        ProcessArtifact(
            "prompt.skills",
            PROCESS_ARTIFACT_CODE,
            prompt_version,
            path=".agents/skills/**/SKILL.md docs/agents_snippet.md",
            upstream_artifact_ids=("openspec.requirements", "flowguard.models"),
            description="Model-first kernel, satellite skill, and global snippet prompt guidance.",
        ),
        ProcessArtifact(
            "public.docs",
            PROCESS_ARTIFACT_DOC,
            docs_version,
            path="README.md CHANGELOG.md",
            upstream_artifact_ids=("prompt.skills",),
            description="Public release notes and user-facing documentation.",
        ),
        ProcessArtifact(
            "tests.examples",
            PROCESS_ARTIFACT_TEST,
            tests_version,
            path="tests/ examples/",
            upstream_artifact_ids=("prompt.skills", "flowguard.models"),
            description="Regression tests and executable skill-trigger review model.",
        ),
        ProcessArtifact(
            "installed.local",
            PROCESS_ARTIFACT_RELEASE,
            install_version,
            path="editable package + <skills-root>",
            upstream_artifact_ids=("prompt.skills", "public.docs", "tests.examples"),
            description="Editable package plus global installed skill/prompt files.",
        ),
        ProcessArtifact(
            "shadow.workspace",
            PROCESS_ARTIFACT_RELEASE,
            shadow_version,
            path="<workspace>/FlowGuard",
            upstream_artifact_ids=("prompt.skills", "public.docs", "tests.examples"),
            description="Local shadow workspace used by Codex skills.",
        ),
        ProcessArtifact(
            "git.state",
            PROCESS_ARTIFACT_RELEASE,
            git_version,
            path="git commit/tag/push",
            upstream_artifact_ids=(
                "openspec.requirements",
                "prompt.skills",
                "public.docs",
                "tests.examples",
                "installed.local",
                "shadow.workspace",
            ),
            description="Committed repository state and pushed tag.",
        ),
        ProcessArtifact(
            "github.release",
            PROCESS_ARTIFACT_RELEASE,
            release_version,
            path="GitHub Release v0.18.4",
            upstream_artifact_ids=("git.state",),
            description="Published GitHub release.",
        ),
    )


def release_plan() -> DevelopmentProcessPlan:
    return DevelopmentProcessPlan(
        "flowguard-v0.18.4-model-visibility-release",
        artifacts=release_artifacts(),
        actions=(
            ProcessAction(
                "propose-requirements",
                writes_artifacts=("openspec.requirements",),
                description="Capture routing and visibility requirements.",
            ),
            ProcessAction(
                "model-prompt-behavior",
                writes_artifacts=("flowguard.models",),
                order_after=("propose-requirements",),
                description="Build executable local FlowGuard checks for model visibility.",
            ),
            ProcessAction(
                "edit-prompts-and-docs",
                writes_artifacts=("prompt.skills", "public.docs", "tests.examples"),
                order_after=("model-prompt-behavior",),
                description="Strengthen prompt guidance and regression tests.",
            ),
            ProcessAction(
                "run-models-and-tests",
                produced_evidence_ids=(
                    "model-visibility-checks",
                    "skill-trigger-review",
                    "focused-tests",
                    "openspec-strict",
                    "skill-doc-validation",
                    "full-regression",
                ),
                order_after=("edit-prompts-and-docs",),
                description="Run executable model checks, OpenSpec validation, and regressions.",
            ),
            ProcessAction(
                "sync-local-install",
                writes_artifacts=("installed.local", "shadow.workspace"),
                produced_evidence_ids=("install-sync-check", "shadow-sync-check"),
                order_after=("run-models-and-tests",),
                description="Sync editable install, global skills, and shadow workspace.",
            ),
            ProcessAction(
                "prepare-git-release",
                writes_artifacts=("git.state",),
                produced_evidence_ids=("privacy-scan", "git-clean-release-state"),
                order_after=("sync-local-install",),
                description="Clean generated files, scan release boundary, commit, tag, and push.",
            ),
            ProcessAction(
                "publish-github-release",
                action_type="claim_release",
                writes_artifacts=("github.release",),
                produced_evidence_ids=("github-release-view",),
                required_validation_ids=(
                    "models-current",
                    "openspec-current",
                    "tests-current",
                    "skill-docs-current",
                    "install-local-current",
                    "shadow-current",
                    "privacy-current",
                    "git-current",
                    "github-release-current",
                ),
                order_after=("prepare-git-release",),
                decision_scope=PROCESS_SCOPE_RELEASE,
                description="Create GitHub Release only after current validation evidence exists.",
            ),
        ),
        evidence=(
            ProcessEvidence(
                "model-visibility-checks",
                evidence_kind="flowguard_model",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("flowguard.models", "prompt.skills"),
                covered_versions={"flowguard.models": "2", "prompt.skills": "2"},
                validation_requirement_ids=("models-current",),
                produced_by_action_id="run-models-and-tests",
                command="python .flowguard/model_visibility/run_checks.py",
            ),
            ProcessEvidence(
                "skill-trigger-review",
                evidence_kind="flowguard_model",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("tests.examples", "prompt.skills"),
                covered_versions={"tests.examples": "2", "prompt.skills": "2"},
                validation_requirement_ids=("models-current", "tests-current"),
                produced_by_action_id="run-models-and-tests",
                command="python examples/flowguard_skill_trigger/run_review.py",
            ),
            ProcessEvidence(
                "focused-tests",
                evidence_kind="pytest",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("tests.examples", "prompt.skills", "public.docs"),
                covered_versions={"tests.examples": "2", "prompt.skills": "2", "public.docs": "2"},
                validation_requirement_ids=("tests-current",),
                produced_by_action_id="run-models-and-tests",
                command="python -m pytest tests/test_skill_docs.py tests/test_flowguard_skill_trigger.py -q",
            ),
            ProcessEvidence(
                "openspec-strict",
                evidence_kind="openspec",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("openspec.requirements",),
                covered_versions={"openspec.requirements": "2"},
                validation_requirement_ids=("openspec-current",),
                produced_by_action_id="run-models-and-tests",
                command="openspec validate --all --strict",
            ),
            ProcessEvidence(
                "skill-doc-validation",
                evidence_kind="skill_validation",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("prompt.skills",),
                covered_versions={"prompt.skills": "2"},
                validation_requirement_ids=("skill-docs-current",),
                produced_by_action_id="run-models-and-tests",
                command="quick_validate.py .agents/skills/*",
            ),
            ProcessEvidence(
                "full-regression",
                evidence_kind="regression",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("tests.examples", "prompt.skills", "public.docs"),
                verifier_artifacts=("tests.examples",),
                covered_versions={"tests.examples": "2", "prompt.skills": "2", "public.docs": "2"},
                validation_requirement_ids=("tests-current",),
                produced_by_action_id="run-models-and-tests",
                command="python -m pytest -q && python -m unittest discover -s tests",
            ),
            ProcessEvidence(
                "install-sync-check",
                evidence_kind="install_sync",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("installed.local", "prompt.skills", "public.docs"),
                covered_versions={"installed.local": "2", "prompt.skills": "2", "public.docs": "2"},
                validation_requirement_ids=("install-local-current",),
                produced_by_action_id="sync-local-install",
                command="python -m pip install -e . && python -c \"import flowguard; print(flowguard.__version__)\"",
            ),
            ProcessEvidence(
                "shadow-sync-check",
                evidence_kind="shadow_sync",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("shadow.workspace", "prompt.skills", "public.docs"),
                covered_versions={"shadow.workspace": "2", "prompt.skills": "2", "public.docs": "2"},
                validation_requirement_ids=("shadow-current",),
                produced_by_action_id="sync-local-install",
                command="shadow workspace file comparison and focused tests",
            ),
            ProcessEvidence(
                "privacy-scan",
                evidence_kind="release_boundary",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("public.docs", "prompt.skills", "git.state"),
                covered_versions={"public.docs": "2", "prompt.skills": "2", "git.state": "2"},
                validation_requirement_ids=("privacy-current",),
                produced_by_action_id="prepare-git-release",
                command="rg release-boundary and secret scans",
            ),
            ProcessEvidence(
                "git-clean-release-state",
                evidence_kind="git_release",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("git.state",),
                covered_versions={"git.state": "2"},
                validation_requirement_ids=("git-current",),
                produced_by_action_id="prepare-git-release",
                command="git status, git tag, git push",
            ),
            ProcessEvidence(
                "github-release-view",
                evidence_kind="github_release",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("github.release", "git.state"),
                covered_versions={"github.release": "2", "git.state": "2"},
                validation_requirement_ids=("github-release-current",),
                produced_by_action_id="publish-github-release",
                command="gh release view v0.18.4",
            ),
        ),
        validation_requirements=(
            ValidationRequirement(
                "models-current",
                required_artifact_ids=("flowguard.models", "prompt.skills"),
                required_evidence_kinds=("flowguard_model",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "openspec-current",
                required_artifact_ids=("openspec.requirements",),
                required_evidence_kinds=("openspec",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "tests-current",
                required_artifact_ids=("tests.examples",),
                required_evidence_kinds=("pytest", "regression", "flowguard_model"),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "skill-docs-current",
                required_artifact_ids=("prompt.skills",),
                required_evidence_kinds=("skill_validation",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "install-local-current",
                required_artifact_ids=("installed.local",),
                required_evidence_kinds=("install_sync",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "shadow-current",
                required_artifact_ids=("shadow.workspace",),
                required_evidence_kinds=("shadow_sync",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "privacy-current",
                required_artifact_ids=("git.state",),
                required_evidence_kinds=("release_boundary",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "git-current",
                required_artifact_ids=("git.state",),
                required_evidence_kinds=("git_release",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "github-release-current",
                required_artifact_ids=("github.release",),
                required_evidence_kinds=("github_release",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
        ),
        freshness_rules=(
            FreshnessRule(
                "requirements-change-invalidates-downstream",
                upstream_artifact_id="openspec.requirements",
                invalidates_artifact_ids=("flowguard.models", "prompt.skills", "tests.examples"),
            ),
            FreshnessRule(
                "model-change-invalidates-prompts-and-tests",
                upstream_artifact_id="flowguard.models",
                invalidates_artifact_ids=("prompt.skills", "tests.examples"),
            ),
            FreshnessRule(
                "prompt-change-invalidates-tests-and-installs",
                upstream_artifact_id="prompt.skills",
                invalidates_artifact_ids=("tests.examples", "installed.local", "shadow.workspace"),
            ),
            FreshnessRule(
                "docs-change-invalidates-install-and-git",
                upstream_artifact_id="public.docs",
                invalidates_artifact_ids=("installed.local", "shadow.workspace", "git.state"),
            ),
            FreshnessRule(
                "test-change-invalidates-regression",
                upstream_artifact_id="tests.examples",
                invalidates_artifact_ids=("installed.local", "shadow.workspace", "git.state"),
            ),
            FreshnessRule(
                "install-change-invalidates-git",
                upstream_artifact_id="installed.local",
                invalidates_artifact_ids=("git.state",),
            ),
            FreshnessRule(
                "shadow-change-invalidates-git",
                upstream_artifact_id="shadow.workspace",
                invalidates_artifact_ids=("git.state",),
            ),
            FreshnessRule(
                "git-change-invalidates-release-view",
                upstream_artifact_id="git.state",
                invalidates_artifact_ids=("github.release",),
            ),
        ),
        decision_scope=PROCESS_SCOPE_RELEASE,
        release_deferred_allowed=False,
    )


def broken_stale_release_plan() -> DevelopmentProcessPlan:
    return DevelopmentProcessPlan(
        "flowguard-v0.18.4-broken-stale-release",
        artifacts=release_artifacts(prompt_version="3", git_version="3"),
        actions=(
            ProcessAction("run-old-tests", produced_evidence_ids=("old-focused-tests",)),
            ProcessAction("peer-edits-prompts", actor="peer", writes_artifacts=("prompt.skills",)),
            ProcessAction("tag-without-resync", writes_artifacts=("git.state",)),
            ProcessAction(
                "publish-with-old-evidence",
                action_type="claim_release",
                required_validation_ids=("tests-current", "git-current"),
                decision_scope=PROCESS_SCOPE_RELEASE,
            ),
        ),
        evidence=(
            ProcessEvidence(
                "old-focused-tests",
                evidence_kind="pytest",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("tests.examples", "prompt.skills"),
                covered_versions={"tests.examples": "2", "prompt.skills": "2"},
                validation_requirement_ids=("tests-current",),
                produced_by_action_id="run-old-tests",
                command="python -m pytest tests/test_skill_docs.py tests/test_flowguard_skill_trigger.py -q",
            ),
            ProcessEvidence(
                "old-git-state",
                evidence_kind="git_release",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("git.state", "github.release"),
                covered_versions={"git.state": "2", "github.release": "2"},
                validation_requirement_ids=("git-current",),
                produced_by_action_id="run-old-tests",
                command="git status && gh release view",
            ),
        ),
        validation_requirements=(
            ValidationRequirement(
                "tests-current",
                required_artifact_ids=("tests.examples",),
                required_evidence_kinds=("pytest",),
                evidence_ids=("old-focused-tests",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
            ValidationRequirement(
                "git-current",
                required_artifact_ids=("git.state", "github.release"),
                required_evidence_kinds=("git_release",),
                evidence_ids=("old-git-state",),
                scope=PROCESS_SCOPE_RELEASE,
                release_required=True,
            ),
        ),
        freshness_rules=(
            FreshnessRule(
                "prompt-change-invalidates-tests-and-installs",
                upstream_artifact_id="prompt.skills",
                invalidates_artifact_ids=("tests.examples", "installed.local", "shadow.workspace"),
            ),
        ),
        decision_scope=PROCESS_SCOPE_RELEASE,
        release_deferred_allowed=False,
    )


def run_checks():
    return (
        review_development_process_flow(release_plan()),
        review_development_process_flow(broken_stale_release_plan()),
    )
